//
// Created by Ryan on 2023/2/5.
//

#ifndef RYAN_FFMPEG_PLAYER_FFMPEGMEDIAPLAYER_JNI_H
#define RYAN_FFMPEG_PLAYER_FFMPEGMEDIAPLAYER_JNI_H

#include <jni.h>

#endif //RYAN_FFMPEG_PLAYER_FFMPEGMEDIAPLAYER_JNI_H
