/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ryan_ffmpeg_player_media_FFMediaPlayer */

#ifndef _Included_ryan_ffmpeg_player_media_FFMediaPlayer
#define _Included_ryan_ffmpeg_player_media_FFMediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ryan_ffmpeg_player_media_FFMediaPlayer
 * Method:    _prepare
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ryan_1ffmpeg_1player_media_FFMediaPlayer__1prepare
  (JNIEnv *, jobject);

/*
 * Class:     ryan_ffmpeg_player_media_FFMediaPlayer
 * Method:    _setDataSource
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ryan_1ffmpeg_1player_media_FFMediaPlayer__1setDataSource
  (JNIEnv *, jobject);

/*
 * Class:     ryan_ffmpeg_player_media_FFMediaPlayer
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ryan_1ffmpeg_1player_media_FFMediaPlayer__1init
  (JNIEnv *, jobject);

/*
 * Class:     ryan_ffmpeg_player_media_FFMediaPlayer
 * Method:    _unInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ryan_1ffmpeg_1player_media_FFMediaPlayer__1unInit
  (JNIEnv *, jobject);

/*
 * Class:     ryan_ffmpeg_player_media_FFMediaPlayer
 * Method:    _streamOpen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ryan_1ffmpeg_1player_media_FFMediaPlayer__1streamOpen
  (JNIEnv *, jobject);

/*
 * Class:     ryan_ffmpeg_player_media_FFMediaPlayer
 * Method:    _destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ryan_1ffmpeg_1player_media_FFMediaPlayer__1destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
